import {
  Button,
  Card,
  CardBody,
  CardFooter,
  CardHeader,
  Flex,
  Link,
  Text,
} from "@chakra-ui/react";

const publications = [
  {
    title:
      "Design Tools for Supporting the Remote Collaborative Design Process: A Systematic Review",
    tag: "Ye, X., Frens, J. W. & Hu, J., Nov 2022, (Accepted/In press) The Tenth International Symposium of Chinese CHI (Chinese CHI 2022). 13 p.",
    abstract:
      "As design collaboration shifts from co-located to remote, both human-computer interaction (HCI) and Computer-Supported Cooperative Work (CSCW) have been seeking ways to support distributed collaborative design processes. We noticed that a lot of studies focused on the early phase co-ideation process, i.e., brainstorming and sketching, while the later phase co-exploration through iterative prototyping remains relatively unexplored. Therefore, improving the remote collaborative design process remains a research challenge. This literature review elaborates on the current supporting tools and their corresponding strategies during different design practices. We contribute an overview of the design space for improving the remote collaborative design processes. Moreover, we identified gaps and opportunities for future research and tool development in the remote collaborative design process. We end this paper by concluding the insights with a research agenda for our future research.",
    link: "https://doi.org/10.1145/3565698.3565772",
  },
  {
    title:
      "Exploring Future Tools for Supporting Remote Collaborative Prototyping Process",
    tag: "Ye, X., Frens, J. W. & Hu, J., Nov 2022, With Design: Reinventing Design Modes: Proceedings of the 9th Congress of the International Association of Societies of Design Research (IASDR 2021). Springer Nature, p. 2806-2820 13 p.",
    abstract:
      "This pictorial presents a qualitative study of designers’ visions of remote collaborative prototyping process in the future. Twelve sketches were generated by eight participants, which provided the basis for us to construct new supportive tools. We analyse their drawings and summarise the findings. 5 themes with 6 sub-themes were identified related to the design ideas for the tools in the future remote collaboration. We conclude the pictorial by proposing our initial ideas to improve the prototyping process in the remote collaborative design teams.",
    link: "https://doi.org/10.1007/978-981-19-4472-7_181",
  },
  {
    title:
      "Adjusting to a Distributed Collaborative Design Process During the COVID-19 Pandemic",
    tag: "Ye, X., Frens, J. W. & Hu, J., 4 Oct 2021, In: IEEE Pervasive Computing. 20, 4, p. 9-17 9 p.",
    abstract:
      "Due to the sudden transition towards online learning caused by COVID-19, we realized the urgency of deepening our understanding of the distributed collaborative design process. We conducted critical incident interviews to identify the challenges that design students and professional designers encountered and how they overcame them in their work. Based on the insights from this first study, we carried out an online survey to corroborate our insights. We found that the shift towards online meetings impacts the collaborative design process. Most notably it causes reduced co-exploration in the design process, especially on and with physical objects. This leads us to the conclusion that the current strategies are not adequate for facilitating designers who collaborate remotely. Following our insights, we provide suggestions for enhancing the supporting tools for the distributed collaborative design process.",
    link: "https://doi.org/10.1109/MPRV.2021.3111448",
  },
];

export function Papers() {
  return (
    <Flex direction="column" gap={8} margin="0 auto" maxW="800px">
      {publications.map((publication) => {
        return (
          <Card>
            <CardHeader>
              <Text fontWeight={"bold"}>{publication.title}</Text>
            </CardHeader>
            <CardBody>
              <Flex direction="column" gap={6}>
                <Text noOfLines={4}>{publication.abstract}</Text>
                <Text fontSize="sm" color="gray.500">
                  {publication.tag}
                </Text>
              </Flex>
            </CardBody>
            <CardFooter>
              <Button as={Link} href={publication.link} target="_blank">
                Link
              </Button>
            </CardFooter>
          </Card>
        );
      })}
    </Flex>
  );
}
